# Site settings
title: DevTo
subtitle: new test
email: your-email@domain.com
description: Test
baseurl: ""
url: "https://app-oszkar.github.io/new"
locale: en
github_username:  KiwiChat

# Build settings
markdown: kramdown
# Outputting
permalink: /:categories/:title/ # pretty
paginate: 5 # amount of posts to show
paginate_path: blog/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

staticman:
  api: "https://api.staticman.ml/v3/entry/github/app-oszkar/new/master/comments"  
#  path: "_data/subdomain/{fileds.subdomain}"
  path: "_data/subdomain/request"
